spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
#    password: JuJiaLe2020!@#
#    password: 1qaz@WSX
